### ISSUE TITLE
Improvement on 'match-regex-and-exported'

### ISSUE THREAD

**Issue by call-a3** [selaux/eslint-plugin-filenames#7]
The rule should also accept the filename if it is 'index' and the parent directory name matches the regex and/or exported name. This is in compliance with the default behaviour of require to use the index file if a directory name is required/imported.

**Comment by selaux** [comment]
Sounds good, will try to do this in the future.

**Comment by call-a3** [comment]
Thanks, I appreciate that.

**Comment by selaux** [comment]
Can you retest current master and see if this implementation works for you.

**Comment by cloudkite** [comment]
@selaux great addition! Have tried it out on a code base with alot of index files and works great!

**Comment by call-a3** [comment]
I get an error stating `The directory 'index' must be named 'state', after the exported value of its index file.`. However, the directory's name is 'state', which is also the name of the default exported function in index.js.

My configuration is 
```yaml
rules:  
    filenames/filenames:  
      - 2  
      - ^[a-zA-Z]+$  
      - match-regex-and-exported  
      - true  
```

Am I doing something wrong or is this a bug in the functionality?
